@WebApi_HostAddress = http://localhost:5070

### Default Weather Forecast (root endpoint)
GET {{WebApi_HostAddress}}/
Accept: application/json

###

### Get all transactions (original endpoint)
GET {{WebApi_HostAddress}}/api/transactions/
Accept: application/json

###

### Get paged transactions - first page (default: page 1, size 10)
GET {{WebApi_HostAddress}}/api/transactions/paged
Accept: application/json

###

### Get paged transactions - first page with specific page size
GET {{WebApi_HostAddress}}/api/transactions/paged?pageNumber=1&pageSize=5
Accept: application/json

###

### Get paged transactions - second page
GET {{WebApi_HostAddress}}/api/transactions/paged?pageNumber=2&pageSize=5
Accept: application/json

###

### Get transaction by ID
GET {{WebApi_HostAddress}}/api/transactions/1
Accept: application/json

###

### Create new transaction
POST {{WebApi_HostAddress}}/api/transactions/
Content-Type: application/json

{
  "customId": "TEST-001",
  "description": "Sample transaction description",
  "transactionDate": "2024-09-15T10:00:00Z",
  "purchaseAmount": 125.50
}

###
